<div class="upperPrint">
  <h1 tabindex="0" id="content">{{title}}</h1>
  <img-path/>
</div>
<p tabindex="0">{{articleContent}}</p>
</div>
<div class="info_art">
    <div id="author">
        <img src="{{authorImg}}">
        <p tabindex="0"><span class="sr">Nome dell'autore autore: </span>{{authorName}}</p>
        <p tabindex="0"><span class="sr">Email dell'autore: </span>{{authorEmail}}</p>
    </div>
    <div id="get_cat">
        <!-- tag che viene sostituito dalle categorie a cui appartiene l'articolo nb=> check se sono settate altrimenti messaggio che non ci sono cateegorie-->
        <span tabindex="0" class="sr">Categorie dell'articolo: </span> <categories />
    </div>
