<fieldset class="cont_art vFlex">
        <legend>Contenuto dell'articolo</legend>
        <label for="titolo_art">Titolo dell'articolo (massimo 126 caratteri)</label>
        <textarea spellcheck="true" maxlength="126" id="titolo_art" rows="2" placeholder="Titolo..." tabindex="0" required>{{title}}</textarea>
        <label for="descr_art">Descrizione articolo (massimo 300 caratteri)</label>
        <textarea spellcheck="true" maxlength="300" id="descr_art" rows="3" placeholder="Descrizione..." tabindex="0" required>{{description}}</textarea>
        <label for="testo_art">Testo dell'articolo (massimo 10000 caratteri)</label>
        <textarea spellcheck="true" maxlength="10000" id="testo_art" rows="10" placeholder="Testo dell'articolo..." tabindex="0" required>{{articleContent}}</textarea>
      </fieldset>