<fieldset class="cont_art vFlex">
  <legend>Contenuto dell'articolo</legend>
  <label for="titolo_art">Titolo dell'articolo (massimo 126 caratteri) <span id="titl_err">Inserisci il titolo dell'articolo e rispetta la lunghezza massima</span></label>
  <textarea name="titolo_art" spellcheck="true" maxlength="126" id="titolo_art" rows="2" placeholder="Titolo..." tabindex="0" required>{{title}}</textarea>
  <label for="descr_art">Descrizione articolo (massimo 300 caratteri) <span id="desc_err">Inserisci la descrizione dell'articolo e rispetta la lunghezza massima</span></label>
  <textarea name="descr_art" spellcheck="true" maxlength="300" id="descr_art" rows="3" placeholder="Descrizione..." tabindex="0" required>{{description}}</textarea>
  <label for="testo_art">Testo dell'articolo (massimo 10000 caratteri) <span id="text_err">Inserisci il testo dell'articolo e rispetta la lunghezza massima</span></label>
  <textarea name="testo_art" spellcheck="true" maxlength="10000" id="testo_art" rows="10" placeholder="Testo dell'articolo..." tabindex="0" required>{{articleContent}}</textarea>
</fieldset>