<div class="hFlex" role="cont_utente">
    <div class="vFlex">
        <img src="{{userImg}}" alt="">
        <strong>Dati personali</strong>
        <p>Nome: {{userName}}</p>
        <p>Cognome: {{userSurname}}</p>
        <p>Email: {{userEmail}}</p>
    </div>
    <div class="vFlex">
        <div>
            <strong>Statistiche</strong>
            <p>Numero di articoli scritti: {{numberOfArticles}}</p>
            <p>Numero di like messi: {{givenLikes}}</p>
            <p>Numero di like ricevuti: {{receivedLikes}}</p>
        </div>
        <userAdminOption />
    </div>
</div>