<div class="hFlex" role="cont_utente">
    <div class="vFlex">
        <img src="{{userImg}}" alt="">
        <strong tabindex="0">Dati personali</strong>
        <p tabindex="0">Nome: {{userName}}</p>
        <p tabindex="0">Cognome: {{userSurname}}</p>
        <p tabindex="0">Email: {{userEmail}}</p>
    </div>
    <div class="vFlex">
        <div>
            <strong tabindex="0">Statistiche</strong>
            <p tabindex="0">Numero di articoli scritti: {{numberOfArticles}}</p>
            <p tabindex="0">Numero di like messi: {{givenLikes}}</p>
            <p tabindex="0">Numero di like ricevuti: {{receivedLikes}}</p>
        </div>
        <userAdminOption />
    </div>
</div>